apiVersion: v1
kind: Secret
metadata:
  name: auth-target-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  POSTGRES_USER: dGFyZ2V0aW5n
  POSTGRES_PASSWORD: dGFyZ2V0aW5n
  POSTGRES_DB: dGFyZ2V0aW5n