services:
  localstack:
    image: localstack/localstack:3.0
    container_name: localstack
    environment:
      SERVICES: dynamodb,sqs
      AWS_DEFAULT_REGION: us-east-1
    ports:
      - "4566:4566" # endpoint unificado
    volumes:
      - "./localstack:/var/lib/localstack"

  analytics-service:
    build: .
    container_name: analytics-service
    depends_on:
      - localstack
    environment:
      PORT: 8005
      AWS_REGION: us-east-1
      AWS_SQS_URL: http://localstack:4566/000000000000/analytics-queue
      AWS_DYNAMODB_TABLE: analytics-events
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_SQS_ENDPOINT: http://localstack:4566
      AWS_DYNAMODB_ENDPOINT: http://localstack:4566
    ports:
      - "8005:8005"
