apiVersion: v1
kind: Secret
metadata:
  name: flag-app-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  DATABASE_URL: cG9zdGdyZXM6Ly9hZG1pbjphZG1pbjEyM0BmbGFnLXBvc3RncmVzOjU0MzIvZmxhZ3NkYg==
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZTo4MDAx