apiVersion: v1
kind: Secret
metadata:
  name: localstack-app-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  SERVICES: c3FzLGR5bmFtb2Ri
  AWS_DEFAULT_REGION: dXMtZWFzdC0x
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==