apiVersion: v1
kind: Secret
metadata:
  name: auth-app-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  MASTER_KEY: bWluaGFfbWFzdGVyX2tleV9zdXBlcl9zZWNyZXRh
  DATABASE_URL: cG9zdGdyZXM6Ly9hdXRoX3VzZXI6YXV0aF9wYXNzQGF1dGgtZGI6NTQzMi9hdXRoX2RiP3NzbG1vZGU9ZGlzYWJsZQ==