apiVersion: v1
kind: Secret
metadata:
  name: analytics-app-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  PORT: ODAwNQ==
  AWS_REGION: dXMtZWFzdC0x
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  AWS_SQS_URL: aHR0cDovL2xvY2Fsc3RhY2s6NDU2Ni8wMDAwMDAwMDAwMDAvZXZhbHVhdGlvbi1ldmVudHM=
  AWS_SQS_ENDPOINT: aHR0cDovL2xvY2Fsc3RhY2s6NDU2Ng==
  AWS_DYNAMODB_TABLE: VG9nZ2xlTWFzdGVyQW5hbHl0aWNz
  AWS_DYNAMODB_ENDPOINT: aHR0cDovL2xvY2Fsc3RhY2s6NDU2Ng==