apiVersion: v1
kind: Secret
metadata:
  name: auth-flag-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  POSTGRES_USER: YWRtaW4=
  POSTGRES_PASSWORD: YWRtaW4xMjM=
  POSTGRES_DB: ZmxhZ3NkYg==