apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: togglemaster
  labels:
    app: targeting-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
      - name: targeting-service
        image: 397233770793.dkr.ecr.us-east-1.amazonaws.com/targeting-service:latest
        ports:
        - containerPort: 8003
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 20
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 10
        envFrom:
        - secretRef:
            name: targeting-service-secret
