apiVersion: v1
kind: Secret
metadata:
  name: evaluation-app-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  PORT: ODAwNA==
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5
  FLAG_SERVICE_URL: aHR0cDovL2ZsYWctc2VydmljZTo4MDAy
  TARGETING_SERVICE_URL: aHR0cDovL3RhcmdldGluZy1zZXJ2aWNlOjgwMDM=
  AWS_ACCESS_KEY_ID: dGVzdA==
  AWS_SECRET_ACCESS_KEY: dGVzdA==
  AWS_REGION: dXMtZWFzdC0x
  AWS_SQS_URL: aHR0cDovL2xvY2Fsc3RhY2s6NDU2Ni8wMDAwMDAwMDAwMDAvZXZhbHVhdGlvbi1ldmVudHM=
  AWS_SQS_ENDPOINT: aHR0cDovL2xvY2Fsc3RhY2s6NDU2Ng==