apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: togglemaster
spec:
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: marcelosilva404/targeting-service:1.0
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          env:
            - name: PORT
              value: "8003"
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: target-app-secret
                  key: DATABASE_URL
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: target-app-secret
                  key: AUTH_SERVICE_URL
          ports:
            - containerPort: 8003
          livenessProbe: 
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe: 
            httpGet:
              path: /health
              port: 8003
            initialDelaySeconds: 5
            periodSeconds: 5