apiVersion: v1
kind: Secret
metadata:
  name: target-app-secret
  namespace: togglemaster
type: Opaque
data:
  # Os valores DEVEM estar em base64
  DATABASE_URL: cG9zdGdyZXM6Ly90YXJnZXRpbmc6dGFyZ2V0aW5nQHRhcmdldGluZy1kYjo1NDMyL3RhcmdldGluZw==
  AUTH_SERVICE_URL: aHR0cDovL2F1dGgtc2VydmljZTo4MDAx